# Generated by Django 4.1.1 on 2022-10-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=255)),
                ('service_date', models.DateTimeField()),
                ('service_details', models.CharField(max_length=255)),
                ('service_bill', models.IntegerField()),
            ],
        ),
    ]
