# Generated by Django 4.1.1 on 2022-10-02 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carservice',
            name='city',
            field=models.CharField(default='delhi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carservice',
            name='contact',
            field=models.IntegerField(default=32443),
            preserve_default=False,
        ),
    ]
